### ISSUE TITLE
LookupError: --NOVALUE-- when accessing properties-tab

### ISSUE THREAD

**Issue by ida** [collective/Solgema.fullcalendar#45]
Steps to reproduce:
- Install a Plone-4.3.3 site
- Activate Solgema.fullcalendar-2.3.3
- Set the 'events'-folder's view to 'Solgema Fullcalendar'
- Click on 'Calendar properties'

Full traceback:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in **call**
  Module plone.z3cform.layout, line 60, in update
  Module z3c.form.form, line 158, in render
  Module zope.browserpage.viewpagetemplatefile, line 51, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in **call**
  Module zope.tal.talinterpreter, line 271, in **call**
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module zope.tales.tales, line 696, in evaluate
- URL: /home/editha/.buildout/eggs/plone.app.z3cform-0.7.6-py2.7.egg/plone/app/z3cform/templates/macros.pt
- Line 97, Column 46
- Expression: <PathExpr standard:u'widget/@@ploneform-render-widget'>
- Names:
    {'args': (),
     'context': <Collection at /97/events/aggregator>,
     'default': <object object at 0x7f87055ebb00>,
     'loop': {},
     'nothing': None,
     'options': {},
     'repeat': {},
     'request': <HTTPRequest, URL=http://v37211.1blu.de:8888/97/events/aggregator/@@solgemafullcalendar_properties>,
     'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x6c262d0>,
     'view': <Solgema.fullcalendar.browser.content.SolgemaFullcalendarTopicFormBase object at 0xc572610>,
     'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0xc624cd0>}
  Module zope.tales.expressions, line 217, in **call**
  Module Products.PageTemplates.Expressions, line 155, in _eval
  Module Products.PageTemplates.Expressions, line 117, in render
  Module Products.Five.browser.metaconfigure, line 479, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 83, in **call**
  Module zope.browserpage.viewpagetemplatefile, line 51, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in **call**
  Module zope.tal.talinterpreter, line 271, in **call**
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module zope.tales.tales, line 696, in evaluate
- URL: /home/editha/.buildout/eggs/plone.app.z3cform-0.7.6-py2.7.egg/plone/app/z3cform/templates/widget.pt
- Line 37, Column 4
- Expression: <PathExpr standard:u'widget/render'>
- Names:
    {'args': (),
     'context': <ContentTreeWidget 'form.widgets.target_folder'>,
     'default': <object object at 0x7f87055ebb00>,
     'loop': {},
     'nothing': None,
     'options': {},
     'repeat': {},
     'request': <HTTPRequest, URL=http://v37211.1blu.de:8888/97/events/aggregator/@@solgemafullcalendar_properties>,
     'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x6e22550>,
     'view': <Products.Five.metaclass.RenderWidget object at 0xc620910>,
     'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0xc6240d0>}
  Module zope.tales.expressions, line 217, in **call**
  Module zope.tales.expressions, line 211, in _eval
  Module plone.formwidget.contenttree.widget, line 168, in render
  Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 51, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in **call**
  Module zope.tal.talinterpreter, line 271, in **call**
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module zope.tales.tales, line 696, in evaluate
- URL: /home/editha/.buildout/eggs/plone.formwidget.contenttree-1.0.7-py2.7.egg/plone/formwidget/contenttree/input.pt
- Line 3, Column 5
- Expression: <PathExpr standard:u'view/renderQueryWidget'>
- Names:
    {'args': (<ContentTreeWidget 'form.widgets.target_folder'>,),
     'context': <Collection at /97/events/aggregator>,
     'default': <object object at 0x7f87055ebb00>,
     'loop': {},
     'nothing': None,
     'options': {},
     'repeat': {},
     'request': <HTTPRequest, URL=http://v37211.1blu.de:8888/97/events/aggregator/@@solgemafullcalendar_properties>,
     'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x628c990>,
     'view': <ContentTreeWidget 'form.widgets.target_folder'>,
     'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0xc61c0d0>}
  Module zope.tales.expressions, line 217, in **call**
  Module zope.tales.expressions, line 211, in _eval
  Module z3c.formwidget.query.widget, line 212, in renderQueryWidget
  Module z3c.form.widget, line 153, in render
  Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in **call**
  Module zope.tal.talinterpreter, line 271, in **call**
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module zope.tales.tales, line 696, in evaluate
- URL: /home/editha/.buildout/eggs/z3c.form-3.1.1-py2.7.egg/z3c/form/browser/radio_input.pt
- Line 8, Column 4
- Expression: <PythonExpr (view.renderForValue(item['value']))>
- Names:
    {'args': (),
     'context': <Collection at /97/events/aggregator>,
     'default': <object object at 0x7f87055ebb00>,
     'loop': {},
     'nothing': None,
     'options': {},
     'repeat': {},
     'request': <HTTPRequest, URL=http://v37211.1blu.de:8888/97/events/aggregator/@@solgemafullcalendar_properties>,
     'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x6d9b6d0>,
     'view': <ContentTreeWidget 'form.widgets.target_folder'>,
     'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0xc613690>}
  Module zope.tales.pythonexpr, line 59, in **call**
- **traceback_info**: (view.renderForValue(item['value']))
  Module <string>, line 1, in <module>
  Module z3c.form.browser.radio, line 44, in renderForValue
  Module z3c.form.term, line 38, in getTermByToken
  Module zope.schema.vocabulary, line 133, in getTermByToken
  LookupError: --NOVALUE--

**Comment by pefu** [comment]
Jens W. Klein mentiioned this issue on plone-users mailing list today.

For new users of Plone it is hard to fix such a problem. I've read the 
comments here carefully and got the impression that this problem is
still present with Plone 4.3.5 and can only be worked around by pinning
z3c.form to an older version 3.0.5 .  Is my understanding correct?

**Comment by chucktheobald** [comment]
Confirmed for Plone 4.3.3, I'm not yet at version 4.3.5, though. Pinning z3c.form to version 3.0.5 allows the Calendar properties to work.
Agree that this is hard to fix for a new user, I speak as one with less than a year of experience with Plone and that not full-time.
I would think that Solgema.fullcalendar would have a way to require version <=3.0.5 until z3c.form is fixed.
